name: autoPR

on:
  push:

jobs:
  cleanup-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: List Runners
        shell: bash
        run: |
          export GITHUB_PAT=`echo ${{ secrets.RUNNER_PAT }}`
          json_response=$(curl -sX GET -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $GITHUB_PAT" https://api.github.com/repos/arimaverick/terraform-repo/actions/runners)
          total_cnt=`echo $json_response | jq .total_count`
          echo "Total Runners: $total_cnt"
          cnt=0
          a=0
          #for i in $(seq 0 1 $total_runners_cnt)
          while [  $cnt -lt $total_cnt ]
          do
            echo "Checking runner $cnt"
            status=`echo $json_response | jq -r .runners[$cnt].status`
            #echo $status
            if [ $status == 'offline' ]
            then
              runner_id=`echo $json_response | jq .runners[$cnt].id`
              curl -sX DELETE -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $GITHUB_PAT" https://api.github.com/repos/arimaverick/terraform-repo/actions/runners/$runner_id
              a=`expr $a + 1`
            fi 
            cnt=`expr $cnt + 1`
          done
          if [ $a -eq 0 ]
          then 
             echo "Great! There are NO OFFLINE runner today" 
          else
             echo "Total OFFLINE runners deleted: $a"
          fi   
