name: TestDispatcher

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: respondDispatcher
    #env:
    #  GITHUB_TOKEN: {{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-18.04
    steps: 
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.client_payload.ref }}
    - name: dispatcher-trap
      id: dispatchtrap
      env:
        version: ${{ github.event.client_payload.version }}
      run: |
        echo "i ma dispatched, version: $version"      