name: TestDispatcher

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [build]

jobs:
  build:
    name: respondDispatcher
    #env:
    #  GITHUB_TOKEN: {{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-18.04
    steps:     
    - name: dispatcher-trap
      id: dispatchtrap
      with:
        version: ${{ github.event.client_payload.version }}
      run: |
        echo "i ma dispatched, version: $version"      