name: autoPR

on:
  repository_dispatch:

jobs:
  build:
    name: respondDispatcher
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BRANCH: upgrade_version_${{ github.run_id }}
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.client_payload.ref }}
    - name: dispatcher-trap
      id: dispatchtrap
      shell: bash
      env:
        version: ${{ github.event.client_payload.version }}
        LABEL: update version
        repo_token: ${{ secrets.REPO_DISPATCH_PAT }}
      run: |
        #!/bin/bash
        git config --global user.name ${{ github.workflow }}
        git config --global user.email "${{ github.workflow }}@users.noreply.github.com"
        gh api repos/{owner}/{repo}/labels -f name="$LABEL" -f color=2b9bdf -f description="update version" || true
        git checkout -b $BRANCH
        echo "Latest Verion: $version"
        echo $version > version.txt
        git commit -a -m "Update version to $version"
        git push --set-upstream origin $BRANCH
        git config -l
        gh pr create -l "$LABEL" -B main -b "This is an automated PR" -t "Version Update" --reviewer arimaverick
        pr_id=`gh pr list -l "$LABEL" | cut -f1`
        echo "PR Link: $pr_id"
        echo "::set-output name=pr_url::$pr_id"
    - name: automerge-trap
      id: autmerge
      env:
        version: ${{ github.event.client_payload.version }}
        LABEL: update version
        repo_token: ${{ secrets.REPO_DISPATCH_PAT }}
        pr_id: ${{ steps.dispatchtrap.outputs.pr_id }}
      if: ${{ steps.dispatcher.outputs.pr_id }}
      run: |
        #git config --global user.name arimaverick
        #git config --global user.email arimaverick@gmail.com
        export GITHUB_TOKEN=
        echo $repo_token > token.txt
        gh auth login --with-token < token.txt
        rm token.txt
        gh pr review $pr_id --approve -b "interesting"
        gh pr merge $pr_id --merge -d $BRANCH
        #gh pr close $pr_id -d $BRANCH