name: autoPR

on:
  push:
    branches: [main]
  repository_dispatch:

jobs:
  build:
    name: respondDispatcher
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BRANCH: upgrade_version_${{ github.run_id }}
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.client_payload.ref }}
    - name: dispatcher-trap
      id: dispatchtrap
      env:
        version: ${{ github.event.client_payload.version }}
        LABEL: update version
      run: |
        #git config --global user.name ${{ github.workflow }}
        #git config --global user.email "${{ github.workflow }}@users.noreply.github.com"
        git config --global user.name umyfashion
        git config --global user.email umyfashion@gmail.com
        gh api repos/{owner}/{repo}/labels -f name="$LABEL" -f color=2b9bdf -f description="update version" || true
        git checkout -b $BRANCH
        echo "Latest Verion: $version"
        echo $version > version.txt
        git commit -a -m "Update version to $version"
        git push --set-upstream origin $BRANCH
        gh pr create -l "$LABEL" -B main -b "This is an automated PR" -t "Version Update" --reviewer arimaverick
        pr_link=`gh pr list -l "$LABEL"`
        echo $pr_link
        gh pr merge $pr_link --auto --merge
        git config -l | grep user.name
        git config -l | grep user.email
        git config --global user.name arimaverick
        git config --global user.email arimaverick@gmail.com
        git config -l | grep user.name
        git config -l | grep user.email
        gh pr review $pr_link --approve -b "interesting"
        gh pr close $pr_link -d $BRANCH