name: TestDispatcher

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: respondDispatcher
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BRANCH: upgrade_${{}}
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.client_payload.ref }}
    - name: dispatcher-trap
      id: dispatchtrap
      env:
        version: ${{ github.event.client_payload.version }}
      run: |
        git config --global user.name ${{ github.workflow }}
        git config --global user.email "${{ github.workflow }}@users.noreply.github.com"
        git checkout -b $BRANCH
        echo "Latest Verion: $version"
        cat $version > version.txt
        git commit -a -m "Update version to $version"
        git push --set-upstream origin $BRANCH
        gh pr create -B main -b "This is an automated PR"
