name: TestDispatcher

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [build]

jobs:
  build:
     steps:
     env:
      GITHUB_TOKEN: {{ secrets.GITHUB_TOKEN }}
     runs-on: ubuntu-18.04
       - name: dispatcher-trap
         id: dispatchtrap
         run: |
          echo "i ma dispatched"